### PR TITLE
Home page component caching

### LINKED ISSUE #34: Cache The home page
Somehow cache the home page so it only has to load one time.

### PR DESCRIPTION
**Pull request by supriyaamisshra**
Closes #34 

## Summary
- Used react's `useMemo` hook to cache the home page component.

## Acceptance Criteria
- [x] Home page loads only on initial page load
- [x] After a user navigates away from home page, upon return there is no load time

### CODE REVIEW

**Comment by codenamejason** [comment]
I tested this and we still have loading on the Home page load... @supriyaamisshra

**Comment by simplemachine92** [comment]
Here is an example of using localstorage instead of react state. This doesn't completely resolve the loading issue, but it's my progress so far:

https://github.com/moonshotcollective/tokenstream.party/commit/199861a481808fea6236d3d3d37c44fb3eab071f

**Comment by supriyaamisshra** [comment]
*this is still WIP

**Comment by supriyaamisshra** [comment]
I've moved to using a custom memo / cache to load streams data (balance, cap) for the home component.

**Pull request merged**
