### PR TITLE
WIP: Address Copy + Stream Health to Home

### PR DESCRIPTION
**Pull request by simplemachine92**
**Don't merge yet**

Stream addresses added, working on stream-healths to home.

### CODE REVIEW

**Comment by codenamejason** [comment]
dope, thanks for this.

**Comment by simplemachine92** [comment]
Percentages on home, requires a loading indicator.

Screen Shot 2022-01-18 at 5 02 02 PM

Currently re-loads when navigating back to the <Home> view... Maybe we can use local storage... I'd still wait to merge.

**Comment by codenamejason** [comment]
@simplemachine92 your last commit I think created an error when going to a stream.
Screen Shot 2022-01-20 at 11 09 20 AM

This happens when I select the stream from home page.

**Comment by codenamejason** [comment]
I am going to merge this and add a cache layer after. Got a couple more devs coming on board and would be good for one off them to tackle it. @simplemachine92

**Pull request merged**
